apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.net/name: pod-resources
  name: pod-resources
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.net/name: pod-resources
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.net/name: pod-resources
    spec:
      containers:
        - env: []
          image: 'ghcr.io/saidsef/pod-resources:v2024.12'
          imagePullPolicy: Always
          name: pod-resources
          resources:
            limits:
              cpu: 10m
              memory: 15Mi
            requests:
              cpu: 5m
              memory: 5Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
      dnsPolicy: ClusterFirst
      securityContext: {}
      serviceAccountName: pod-resources
      terminationGracePeriodSeconds: 30
